### ISSUE TITLE
How can I predict the item and user rating in the test data?

### ISSUE THREAD

**Issue by miladfa7** [RUCAIBox/RecBole#1056]
I split the dataset into 2 parts **train.inter, test.inter**  (atomic file format).
I trained the BPR model using the train.inter data and then I want to predict the **ratings** test.inter using this model.

It is simply a **test.inter** data structure
```
users_id       items_id          ratings
1                   50
2                   62
...                  ...
```

How can I predict those ratings using the BPR model.?

**Comment by chenyuwuxin** [comment]
@miladfa7 Hello, thanks for your attention to RecBole!
You can set `benchmark_filename` in the configuration file.Let’s assume that the dataset is called `click`, and `benchmark_filename` equals to ['train', 'val', 'test']. That we will load `click.train.inter`, `click.val.inter`, `click.test.inter`, and treat them as train, valid, test dataset. 
You just need to add the following to the `.yaml` file:
`benchmark_filename: ['train','val','test']`

**Comment by miladfa7** [comment]
@chenyuwuxin 
thanks a lot, Can I save the `val.inter ` and `test.inter` files with the predicted ratings?

**Comment by chenyuwuxin** [comment]
@miladfa7 Generally speaking, we will predict the rank of items by score, and calculate the relevant evaluation metrics according to the ranking, rather than the score of the items themselves.If you need to predict the score of `test.inter` file, you can add the code:
```
    input_interaction = test_data.dataset.inter_feat.to(config['device'])
    ratings = model.predict(input_interaction)
```
after:
https://github.com/RUCAIBox/RecBole/blob/7bd3df81edf5554ef65172601f37ef629291d7d5/recbole/quick_start/quick_start.py#L64

In this way, you will get the ratings of the corresponding record of the file.Then you can write them to the file in your own way.
