### ISSUE TITLE
ImportError: cannot import name 'load_data_and_model' from 'recbole.quick_start'

### ISSUE THREAD

**Issue by akokossi** [RUCAIBox/RecBole#1068]
**Describe the bug**
from recbole.quick_start import load_data_and_model
ImportError: cannot import name 'load_data_and_model' from 'recbole.quick_start' (C:\Users\.....\.conda\envs\recbole\lib\site-packages\recbole\quick_start\__init__.py)

**To Reproduce**
1. extra yaml file
2. your code
3. script for running

**Expected behavior**
expected load_data_and_model to be present in recbole.quick_start

**Screenshots**
NA
**Colab Links**
NA
**Desktop (please complete the following information):**
 - OS: Windows]
- RecBole Version most current using conda -c  install aibox recbole
 - Python Version 3.7
- PyTorch Version 1.7.0
- cudatoolkit Version none

**Comment by chenyuwuxin** [comment]
@akokossi Hello, thanks for your attention to RecBole!
This problem is due to the incorrect version of **RecBole** you installed. Please create the conda environment above Python 3.7 before installing **RecBole**. After installation , when you execute the `conda list` command in your conda environment, the version of RecBole should be **1.0.0**.

**Comment by akokossi** [comment]
Thank you that resolved the issue
