### ISSUE TITLE
[🐛BUG] Error while running Yoochose: Keyerror 'user_id'

### ISSUE THREAD

**Issue by nishanthjois** [RUCAIBox/RecBole#1124]
**Describe the bug**

**To Reproduce**
Install RecBole
Run below:
```
from recbole.quick_start import run_recbole
run_recbole(model='ItemKNN', dataset='yoochoose-clicks-merged')

```
**Expected behavior**
I get error KeyError: 'user_id'

Note:
What should be the dataset name for Yoochoose?

**Desktop (please complete the following information):**
 - OS: Linux
- RecBole Version: Latest
 - Python Version: 3.7
- PyTorch Version [e.g. 1.60]
- cudatoolkit Version [e.g. 9.2, none]

**Comment by chenyuwuxin** [comment]
@nishanthjois Hello,thanks for your attention to RecBole!
This problem is because you have not set the running configuration file. Therefore, you need to create a configuration file, A simple example is shown below:
**Yoochose.yaml**
```
# dataset config
field_separator: "\t"
seq_separator: ","
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
load_col:
  inter: [session_id, item_id]
```
And run it with the following command:
`python run_recbole.py --model=ItemKNN --dataset=yoochoose-clicks-merged --config_files=Yoochose.yaml`
I hope my answer can help you.
