### ISSUE TITLE
[💡SUG] Correct splitting of Sequential Recommender Benchmarks

### ISSUE THREAD

**Issue by tzuhsial** [RUCAIBox/RecBole#1135]
**Is your feature request related to a problem? Please describe.**
Lack of correct splitting for Sequential Recommender Benchmark

Taking SASRec (https://arxiv.org/pdf/1808.09781.pdf) as an example

Given a sequence `[1,2,3,4,5]`
We train on `[1,2] -> 3`, valid on `[1,2,3] -> 4` and test on `[1,2,3,4] -> 5`.

**Describe the solution you'd like**
Implementation of sequential recommender evaluation standard splitting and report benchmarking results.

**Describe alternatives you've considered**
N/A

**Additional context**
I was excited to see this codebase since I wanted to use SASRec. I was hesitant at first, since there are no benchmark evaluation results compared with papers despite having implemented these models.  After getting the code running, I looked into the `SequentialDataset` and splitting arguments and found that the splitting does not seem to reflect the benchmark reported in SASRec.   These are the reasons why I have decided to implement my own.

Since this repo is actively maintained and support a wide range of features, an advice here would be to have the benchmark results compared with those reported in papers, so users will be more confident in running the code.

**Comment by leoleojie** [comment]
Hello, thanks for your attention to RecBole!
In RecBole, we performed sequence augmentation on the interaction data.
E.g. Suppose u1 interacts with i1,i2,i3,i4,i5 in time and MAX_ITEM_LIST_LENGTH is 3. After the data augmentation. The sequential dataset becomes {(u1,<i1,0,0>,i2),(u1,<i1,i2,0>,i3),(u1,<i1,i2,i3>,i4),(u1,<i2,i3,i4>,i5)}. That is we're going to match MAX_ITEM_LIST_LENGTH with pad and truncation. Please refer to [our doc](https://recbole.io/docs/_modules/recbole/data/dataset/sequential_dataset.html#SequentialDataset.data_augmentation) and [#issue1060](https://github.com/RUCAIBox/RecBole/issues/1060) for details.
Although different papers have different dataset formats and processing methods, RecBole is a unified code base. Ultimately, it is to make different models reflect a relative result in a unified evaluation system, rather than to reproduce a certain model.
In addition, you are also welcome to submit your implementation in PR. After testing, we will incorporate it into the project and list you as a contributor.
