### ISSUE TITLE
[? Question] Meaning of warning

### ISSUE THREAD

**Issue by mmosc** [RUCAIBox/RecBole#1203]
Hi!
When running RecBole with `ml-100k` as dataset, I keep getting the following two warnings:
```
Max value of item's history interaction records has reached 51.69491525423729% of the total.
Max value of user's history interaction records has reached 35.115864527629235% of the total.
```
I can trace them back in the source code:
https://recbole.io/docs/v0.1.2/_modules/recbole/data/dataset/dataset.html
but I am having troubles understanding what they mean, and especially what `max_col_num` means.

Could you please explain both the variable and the warning?

Thanks!
Marta

**Comment by hyp1231** [comment]
Hi Marta,

Thanks for pointing out that! The warning means that after the preprocessing steps, the density of the dataset is probably too high. For example, `Max value of item's history interaction records has reached 51.69491525423729% of the total.` means that there exists an item, which has been interacted with 50+% users.

If your dataset is naturally very dense, then just don't need to worry. Otherwise, please check the args about data filtering.

By the way, if we organize the interactions as a matrix, `max_col_num` means the number of columns.

Best,
Yupeng

**Comment by mmosc** [comment]
Hi Yupeng, 
thanks a lot for your quick reply! 

Just to check that I understand correctly: 
 - in the case of the `user's history` warning, `max_col_num` is the total number of items, while 
 - in the case of the `item's history` warning, `max_col_num` is the total number of users. 
 Am I getting things right?

Best, 
Marta

**Comment by mmosc** [comment]
Great, thanks! :)
