### ISSUE TITLE
DMF wrong item embedding

### ISSUE THREAD

**Issue by rezash121** [RUCAIBox/RecBole#1209]
I want to get item embedding for the DMF model. When I checked some items embeddings, I realized they were zero. However, when I get item embedding from the BPR model, item embeddings cells are a float number, not zero.
Would you please check it?

**Comment by rezash121** [comment]
Hi, I work with movieLens-100k. Also, I use get_item_embedding(self, item) function.
This is my yaml file configuration.
user_embedding_size: 50
item_embedding_size: 50
item_hidden_size_list: [50,50]
user_hidden_size_list: [50,50]
inter_matrix_type: rating

**Comment by Sherry-XLL** [comment]
@rezash121 Hello, thanks for your attention and feedback! 

Some item embeddings in DMF are indeed zero and the reasons may include two aspects. 

On the one hand, there are **inactive users** and **unpopular items** in the original data set, such as items that have only one interaction. When the data set is divided into training, evaluation and testing sets, some items with few interactions do not appear in the training set, resulting in some zero-value row vectors of `item_matrix` in `get_item_embedding`, and they are still zero after MLP (**M**ulti-**L**ayer **P**erception) transformation of `item_fc_layers`.

https://github.com/RUCAIBox/RecBole/blob/44099680568d17fdd4dc51645ee33f55acb9511e/recbole/model/general_recommender/dmf.py#L162-L180

On the other hand, the default non-linear activation function of `MLPLayers` in `recbole.model.layers` is **ReLU** (**Re**ctified **L**inear **U**nit). 

![ReLU_LeakyReLU](https://user-images.githubusercontent.com/61613449/160320927-9c1f4b6e-a4c1-481b-bf58-10004765c634.jpeg)

Because the gradient of ReLU in the non-positive part is zero, it is very fragile during training, which is likely to lead to **neuronal necrosis** or **dying ReLU problem**. In other words, after `item_fc_layers`, zero-value rows in `item` continue to be zero, and non-zero rows may also become zero due to inappropriate nonlinear activation.

https://github.com/RUCAIBox/RecBole/blob/44099680568d17fdd4dc51645ee33f55acb9511e/recbole/model/layers.py#L54-L55

To alleviate this problem, you can specify other activation functions such as **LeakyReLU** when initializing `MLPLayers` as follows. In this setting, item embeddings from `get_item_embedding` generally does not have all-zero rows except the first one.

```python
self.user_fc_layers = MLPLayers([self.user_embedding_size] + self.user_hidden_size_list, activation='leakyrelu')
self.item_fc_layers = MLPLayers([self.item_embedding_size] + self.item_hidden_size_list, activation='leakyrelu')
```
