### ISSUE TITLE
Steps for creating a Dataset with custom data to train and eval on

### ISSUE THREAD

**Issue by shahjaidev** [RUCAIBox/RecBole#1387]
Hello!

I have user-item interaction data that is currently in a pandas csv with three columns: user_id, item_id, and interaction_weight.

Is there a set of steps/ script to format and convert this data correctly to atomic format to use with the RecBole library? 

I found the guide at "Running a new dataset' on the website
https://recbole.io/docs/user_guide/usage/running_new_dataset.html

(i) https://recbole.io/docs/user_guide/data/atomic_files.html
How exactly can I convert a csv of interaction data to correctly formatted atomic files that are required by the steps?

(ii) 
I see that model='BPR' (for instance) is a parameter to the Config class. I'm curious why we need to pass the model type to construct a dataset? Is there any model-specific transformations that happen?

config = Config(model='BPR', dataset='ml-1m', config_file_list=['ml-1m.yaml'])
dataset = create_dataset(config)

<img width="671" alt="image" src="https://user-images.githubusercontent.com/22052444/184691743-39b34756-8c95-4ff2-a845-0dfc38df09c3.png">

**Comment by shahjaidev** [comment]
I found the guide at "Running a new dataset' on the website
https://recbole.io/docs/user_guide/usage/running_new_dataset.html

I had a few questions: 
(i) https://recbole.io/docs/user_guide/data/atomic_files.html
How exactly can I convert a csv of interaction data to correctly formatted atomic files that are required by the steps?

(ii) 
I see that model='BPR' (for instance) is a parameter to the Config class. I'm curious why we need to pass the model type to construct a dataset? Is there any model-specific transformations that happen?

config = Config(model='BPR', dataset='ml-1m', config_file_list=['ml-1m.yaml'])
dataset = create_dataset(config)

<img width="671" alt="image" src="https://user-images.githubusercontent.com/22052444/184691743-39b34756-8c95-4ff2-a845-0dfc38df09c3.png">

**Comment by leoleojie** [comment]
@shahjaidev Hello, thanks for your attention to RecBole!
1) You can refer to [conversion tools](https://github.com/RUCAIBox/RecSysDatasets/tree/master/conversion_tools). There are some examples for convert original csv dataset to atomic format.
2) Not exactly, we actually process the data according to the type of model it belongs to. Since RecBole supports general recommendation, sequential recommendation, context-aware recommendation and knowledge-based recommendation. Some of them have special process methods. For example, we apply augmentation processing for sequential dataset,  get graph or sparse matrix that describe relations between entities for knowledge dataset and so on.

**Comment by shahjaidev** [comment]
Thanks for the answers! Closing the issue.
