### ISSUE TITLE
Sampling Multiple Negatives

### ISSUE THREAD

**Issue by shahjaidev** [RUCAIBox/RecBole#1388]
https://github.com/RUCAIBox/RecBole/blob/61848c0cc03d25645ebeffbfe9b58c48aaafaa76/run_recbole.py#L13

If I want to use the current quick start (run_recbole.py) and change the trainer such that it uses a dataloader that provides multiple negative samples (as I want to use contrastive loss), where should I make the changes? 

As a follow up, are there any current examples of models inside RecBole that train with multiple negatives?

**Comment by chenyuwuxin** [comment]
@shahjaidev Hello, thanks for your attention to RecBole!
If you want to provide multiple negative samples for each positive sample, you just need to modify the config file. E.g. If you want to sample 2 items for each positive item uniformly, just set: `neg_sampling: {'uniform': 2}`. Then you can utilize `interaction[self.ITEM_ID]` and `interaction[self.NEG_ITEM_ID]` to get the positive sample and its corresponding negative samples. Since most methods use BPR loss, you can refer to the **calculate_loss** function of **SGL** or **LightGCN** for specific usage.

**Comment by shahjaidev** [comment]
Thanks for the answer!

**Comment by shahjaidev** [comment]
Just to confirm, the current implementation of BPR loss in recbole supports multiple negatives right?

**Comment by Sherry-XLL** [comment]
@shahjaidev Yes, negative sampling with multiple negatives for BPR loss is supported in our library. If you have further questions, please feel free to open a new issue.
