### ISSUE TITLE
Trying to understand why LightGCN is this slow + Comparing Training Times

### ISSUE THREAD

**Issue by shahjaidev** [RUCAIBox/RecBole#1398]
Hello!

I'm running Simplex on a large user-item interaction data, ~2 million users and ~2 million items with ~15 million interactions. 

(i) Within each epoch, we iterate through all interactions in train set, correct?

(ii) Despite setting as sparse Embeddings and training on GPU, the training speed is extremely slow (>200 minutes per epoch) compared to 30 s / epoch for BPR on the same data on GPU. 

Could you please point out why this could be the case? And any suggestions to improve the training time?

Thanks!

![image](https://user-images.githubusercontent.com/22052444/185316119-2483219b-2a95-4203-aa3a-926976a93ffc.png)

**Comment by AoiDragon** [comment]
@shahjaidev Hello, here are my answers.

Q1: Yes, you are right.

Q2: It may simply because the dataset is too large. BPR only needs to perform inner product within each batch, while LightGCN needs to perform inner product between all users and items and thus has a much higher time complexity. Considering the large dataset you are using,  the big time cost gap between these two models is not surprising.
