### ISSUE TITLE
Clarifying questions about SimpleX implementation in 1.1.x + SimpleX CUDA OOM issues that are not the case for BPR, other models on same dataset

### ISSUE THREAD

**Issue by shahjaidev** [RUCAIBox/RecBole#1399]
Hi, I had a couple of questions about SimpleX in 1.1.x

(A)
I see that the properties/model/Simplex.yaml file has the following set parameters:
![image](https://user-images.githubusercontent.com/22052444/185334534-48c6ba3c-3e5e-4032-9644-677c08ed001a.png)

About **history_len**
What does this entail in the context of SimpleX? (and curious why default setting is 50)

(i) Only a fixed set of 50 interacted items will be considered during item aggregation step?
OR
(ii) Each time, a randomly sampled set of 50 interacted items for a user will be selected.

(B)
Related to this, is the dataloader for SimpleX iterating over each user, then randomly sampling 1 positive item
OR is it iterating over all user-positive item interactions in an epoch?

(C)
Lastly, are the embeddings mixed one more time with all interacted items before evaluation? (as opposed to using the raw original user embeddings).
In my experiences having implemented SimpleX, using the mixed embeddings provide superior metrics.

If so, I assume this mixing is done with the interacted items for each user, from the train set ...?

(D) **CUDA out of memory error** while training SimpleX with 5 negatives, on same large data (~2 M users, 2 M items, ~15 M interactions) 

Weirdly, I run into the memory error by a large factor when running SimpleX (branch 1.1.x) but with the same configs and on the same data, trains without any issues while using BPR (even though for BPR I set batch_size to 50k). 

The problem is when line 44 _self.history_item_id = self.history_item_id.to(self.device)_
moves the history_item_matrix to the CUDA device. In my case, looks like this matrix is 194.58 GB. Could you suggest a workaround that does not require this?

_RuntimeError: CUDA out of memory. Tried to allocate 194.58 GiB (GPU 0; 47.54 GiB total capacity; 0 bytes already allocated_

Pasting my config file for context:
![image](https://user-images.githubusercontent.com/22052444/185336022-7103c863-6781-4172-8cf3-782186348e1e.png)

Command: 
python run_recbole.py --model=SimpleX --dataset=coclick_1d --config_files=/home/core/shahjaidev/DirectAU/jaidev_configs/simplex_coclick_1d_config.yaml --reg_weight 1e-05

![image](https://user-images.githubusercontent.com/22052444/185335339-9fc3b004-e08b-41a1-ab68-e1ab710e6bd2.png)

**Comment by zhengbw0324** [comment]
@shahjaidev 

(A) `history_len` represents the size of interacted items set of user used in training and testing. During item aggregation step, we only consider a fixed set of 50 interacted items. 

The reason why `history_len` is set to 50 by default is that this setting performs well during our test. You can also adjust the parameters according to the actual situation, or use `run_hyper.py` to search for      hyper-parameters.

(B) It will iterate over all user-positive item interactions in an epoch.

(C) In the process of evaluation, the user’s final embedding is also the aggregation of original user embeddings and the user's interacted items. You can refer to

https://github.com/RUCAIBox/RecBole/blob/c44d9b9a8e67c623040b3ba5f2805643232284d6/recbole/model/general_recommender/simplex.py#L221

(D) Compared with BPR, Simplex is a much more complex model. BPR does not need to use the user's interacted items and has fewer parameters. Therefore, Simplex requires GPU memory much larger than BPR. 

The shape of `history_item_id` is `[num_user,max_history_len]`. `max_ history_ Len` is not `history_len` in the configuration file, but the maximum size of the interacted items set of all users in the dataset. Your dataset has about 2M users and 2M items, so `num_user` is 2M, and `max_history_len` may be very large. This may be the reason why `CUDA out of memory` occurs. 

Our implementation does not consider the very large datasets, so this problem arises. We will optimize this problem as soon as possible. Now you can try to generate user history interaction items yourself. Only generated a small number of interacted items for each user, instead of generating all interacted items and then intercepting some for use. 

Or instead of generating interacted items for all users during model initialization, you can dynamically generated according to a small number of users in each batch during the training process. However, this method may lead to an increase in model training time.
