### ISSUE TITLE
Clarifying questions about Evaluation

### ISSUE THREAD

**Issue by shahjaidev** [RUCAIBox/RecBole#1400]
Some clarification questions :)

(i) Random Split _split: {'RS':[0.95, 0.01, 0.04]}_
is splitting users, right? 

(ii)And how exactly does eval_batch_size come into play? 
Don't the metrics have to be computed on a user level? (e.g. Recall@30 = average user recall @ 30)

(iii) I'm not sure I fully understand the evaluation mode uni100 and pop100. The definitions page says: _uniformly sample 100 negative items for each positive item in testing set, and evaluate the model on these positive items with their sampled negative items._
Does this mean, for computing recall@30 for reach user, the set of target items over which recall is computed and scored is:
(i) ONLY the user's positive items + 100 negative items
OR
(ii) ALL positive items (across different users) in the test set  (call this quantity P) + P*100 negative items
?
Thanks in advance for clearing this confusion :) 

(iv) Even with uni100 eval mode, evaluation is taking several minutes for ~18k users (validation split). I'm curious how evaluation for recall@30 is implemented, specifically what the bottleneck is for taking so long?

(v) Do you have any other tips for speeding up evaluation, on full mode? (Should the eval_batch_size always be set to maximum possible?)

(vi) In 1.1.x is evaluation for metrics like recall@k sped up using FAISS ?

**Comment by shahjaidev** [comment]
Following up on these :)  ?

**Comment by AoiDragon** [comment]
@shahjaidev Hello, 

For Q1: No, _split_ divides interactions in `.inter` files.

For Q2: `eval_batch_size` is to prevent the gpu from being completely occupied. If you have enough gpu memory, you can certainly set the `eval_batch_size` to the size of the evaluation dataset.

For Q3: The former one is correct.

For Q4: It may because the quantity of users is too large.

For Q5: You can set the `eval_batch_size` as big as possible.

For Q6: No.

**Comment by shahjaidev** [comment]
Thanks!
