### ISSUE TITLE
[🐛BUG] How to avoid saving a checkpoint at each training epoch?

### ISSUE THREAD

**Issue by adebiasio-estilos** [RUCAIBox/RecBole#1547]
How can I avoid saving a checkpoint at each training epoch?

**Comment by Sherry-XLL** [comment]
@adebiasio-estilos Hello, Thanks for your attention to RecBole! 

If you do not want to save a checkpoint at each training epoch, you can just set `saved=False` in `run_recbole`.

https://github.com/RUCAIBox/RecBole/blob/d3d421df394a231cd5baebd7a6bc9a05583c6642/run_recbole.py#L49

The parameter `saved (bool, optional)` decides whether to save the model. Defaults to ``True``.

https://github.com/RUCAIBox/RecBole/blob/d3d421df394a231cd5baebd7a6bc9a05583c6642/recbole/quick_start/quick_start.py#L41-L53

**Comment by adebiasio-estilos** [comment]
Hi, thank you for answering! 

If I set saved=False I see the model never save the checkpoint after validation epoch.

Therefore, when I evaluate results on Test set, what epoch is the procedure evaluating? 
The last training epoch or the best validation one?

**Comment by Sherry-XLL** [comment]
Hello @adebiasio-estilos! If you set `saved=False`, the model in the last training epoch will be used for the test set, because the best parameters are not saved. 

When setting `saved=True`, RecBole will not save a checkpoint at every training epoch. Instead, it will save a checkpoint when the results on the evaluation set are better than before. Then, if the best results on the evaluation set do not improve for  `stopping_step` epochs, the checkpoint will not be updated and early-stop strategy is triggered. At last, the test results of the parameters that perform best on the evaluation set will be output.

That is to say, if you do not want to save the best checkpoint at each training epoch, you can not use the best model parameters for test. And if you want to evaluate the model for its optimal performance like most researchers do, `saved=True` is recommended and set by default.

Thanks for your attention to RecBole and feel free to ask questions if you have any problems.

**Comment by adebiasio-estilos** [comment]
Thank you very much for answering!
