### ISSUE TITLE
[🐛BUG] Training time far greater for similar model.

### ISSUE THREAD

**Issue by williamtraynor** [RUCAIBox/RecBole#1715]
Hello, 

I have implemented a model extended from the MacridVAE implementation. When training though, my model ~20 minutes per epoch, takes considerably longer to run than MacridVAE, ~1 minute per epoch. 

I have noticed that while the configurations are the same and the models run on the same dataset, my model has a train_data of length 109 while MacridVAE has a train_data of length 1. I have peered through the code and my configurations and cannot see any reason for there to be a difference in train_data length between the models.

I think if I were to solve this issue then it would fix the training time problem I am having. 

Please let me know if any more information is required.

Thanks, William

**Comment by Sherry-XLL** [comment]
Hello @williamtraynor! Thanks for your attention to RecBole.

MacridVAE is one of the AE-based models in RecBole, and we design a customized function for VAE models to get correct dataloader class, _i.e._, `_get_AE_dataloader` in `/recbole/data/utils.py` as follows:

https://github.com/RUCAIBox/RecBole/blob/23fdeb00f9334b66d23e12b73eb4fd01d413dccd/recbole/data/utils.py#L268-L278

https://github.com/RUCAIBox/RecBole/blob/23fdeb00f9334b66d23e12b73eb4fd01d413dccd/recbole/data/utils.py#L241-L249

The reason why we specialize the dataloader for VAE models is that the training process of models is based on the **list-wise data** with respect to each user (`UserDataLoader`), rather than **point-wise** or **pair-wise** data based on each user-item interaction. Therefore, you can add your own model into the `register_table` of AE models, and your dataloader maybe the same as MacridVAE.

I hope my answers can be helpful to you. If you have any questions, feel free to contact us in this issue.

**Comment by williamtraynor** [comment]
Ahh thank you. That has done the trick. Thanks for your help.

Cheers, William
