### ISSUE TITLE
如果想用自定义的数据训练知识图谱模型，kg文件和link文件的具体内容是什么样的？

### ISSUE THREAD

**Issue by xiaobohe123** [RUCAIBox/RecBole#1724]
通过官方给出的movielens数据集，运行add_knowledge获得的kg文件部分内容如下：

![image](https://user-images.githubusercontent.com/65453235/230820699-623584b4-f820-441b-9195-8ee435783837.png)

kg文件的三元组被定义成这个格式（类似：电影名-film.actor-演员名）
关系类型有film.film.actor也有film.actor.film，两组数据其实表达的是同一内容，是不是取其一就好了，还是两组对称数据必须都存在？

还有一个问题，kg的三元组的头实体和尾实体是否可以是id形式的数字（数值大小会不会导致训练结果有误）？
link文件中entity_id是字符串item_id是数字，可不可以entity_id和item_id直接就是值相同的数字？
![image](https://user-images.githubusercontent.com/65453235/230820867-ca20518f-f488-4745-8098-a535768019ce.png)

**Comment by Wicknight** [comment]
@xiaobohe123 您好！感谢您对RecBole的关注！

1. 目前推荐领域很多kg数据集都存在这种对称的数据，一般情况下二者都要进行使用。当然也可以根据你使用的模型和推荐场景进行更改。
2. .link文件中的entity_id是和.kg文件中的id相对应的，如果能够保证这种一一映射关系就可以进行更改，不会影响结果。

**Comment by xiaobohe123** [comment]
谢谢您的回复，以及成功跑出结果了，感谢大佬们的代码！！！

**Comment by tripledoubleE** [comment]
Hello everyone, 

I am trying to use Recbole in Knowledge-based methods. I could not understand exactly the meaning of the "entity_id" and "item_id" in .link file. 

From your answer, when I translated you said "The 'entity_id' in the .link file corresponds to the 'id' in the .kg file. ". But there is no "id" field in .kg file. I think the reason for my confusion is because of the translation. 

I think that "item_id" is basically the items that we want to recommend (movie, book, ..etc), but I could not solve the entity_id. 

I have 4 relationships in my project:
->User-hotel
->User-transaction
->User-date
->Hotel-RoomType

In the case that "item_id" is HotelId (because I want to recommend hotels); I will miss some relationships, and I will solely use hotel-user and hotel-room_type. In that case, entity IDs are user IDs and room_types. If I do so, is there any problem with the algorithms implemented in the scope of the RecBole?  I am new in this area, so it is very possible that I misunderstood. 

Thank you for your answer in advance.
