### ISSUE TITLE
[🐛BUG] Failed to use yelp dataset because an assertion error is triggered with the .tip file

### ISSUE THREAD

**Issue by pablozivic** [RUCAIBox/RecBole#1740]
**Description**
When using the yelp dataset 

An assertion error is thrown in the line 

```python
assert suf in {'.inter', '.user', '.item'}
```
That is because `suf=="tip"`
 
**To Reproduce**
 running the following code. I'm using recbole 1.0.1, because when using recbole 1.1.1 there is another error that is thrown after downloading the dataset with a torch.distributed.barrier() being called before init_process_group

```python
from recbole import quick_start
config_dict = {
    'threshold': {'rating': 4},
    'load_col': {
        'inter': ['user_id', 'item_id', 'rating']
    }
}


quick_start.run_recbole(model='LR', dataset='yelp', config_dict=config_dict)
```

**Expected behavior**
I would expect to be able to use the dataset without having to delete the .tip file. Moreover, I would like to be able to use the .tip file.

**Desktop (please complete the following information):**
 - OS: Linux
- RecBole Version 1.0.1
 - Python Version 3.7.9
- PyTorch Version 1.13.1
- cudatoolkit Version: - not applicable, I am testing everything in CPU

**Comment by leoleojie** [comment]
@pablozivic Hello, thanks for your attention to RecBole. 
Yes, it is a bug in RecBole 1.0.1 and we have fix it in the latest version (1.1.1). Actually, it is just used to check if you downloaded the correct dataset (without other suffixes). And you can choose to use the latest version or you can also delete [this line of code](https://github.com/RUCAIBox/RecBole/blob/v1.0.1/recbole/utils/url.py#L109) in `/recbole/utils/url.py` of recbole packages, since it does not affect other functions.

**Comment by pablozivic** [comment]
Thanks a lot!!!

**Comment by panhaoyu** [comment]
hello, could you please recheck the issue? seems the issue still exists in 1.1.1

**Comment by panhaoyu** [comment]
It seems that the code in the repo have fixed the bug, but the pypi package still remain the wrong code. Could you please update the package?
