### ISSUE TITLE
[💡SUG] A new tutorial to customized model

### ISSUE THREAD

**Issue by rowedenny** [RUCAIBox/RecBole#489]
**Is your feature request related to a problem? Please describe.**
Following the documentation, I am able to customize a new model of my own. Then I would like to embed my model with the current quick start tutorial, to run through the pipeline.

However, I find it is hard to make it. Looking through the repo, the challenge here is get_model will automatically select a model class based on model name, not including the customized model. (Please correct me if my understanding is wrong)
https://github.com/RUCAIBox/RecBole/blob/2e156473267d8b869fbeffc92b409ce474390f6d/recbole/config/configurator.py#L208

I also notice that the model is created, get_model is called again later, 
https://github.com/RUCAIBox/RecBole/blob/master/recbole/quick_start/quick_start.py#L45

In summary, to create a model we need to provide config and dataset, however, to successfully create a config, it requires going through the function get_model. This function only retrieves all the existing models.  At least, if we follow the tutorial of quick-start, we cannot train a customized model.

**Describe the solution you'd like**
For the function get_model, if we cannot find the existing module named "model_name", search it additionally where the path can be specified by the user-self. This path provides the module for the customized model. 
https://github.com/RUCAIBox/RecBole/blob/2e156473267d8b869fbeffc92b409ce474390f6d/recbole/utils/utils.py#L43

**Describe alternatives you've considered**
Would it possible to provide a tutorial introducing the pipeline for a customized model/trainer/sampler?

**Comment by ShanleiMu** [comment]
Thanks for your suggestion! It's indeed hard to customize a new model and run it with RecBole in the previous version. 

We have made a improvement (refer to #490 ), which makes the Config Module can receive model class (e.g. BPR, NewModel) to complete the initialization of config. 

When you run a new model, you can create a config with the model class instead of the model name. That will avoid calling `get_model()`. You can refer to this example (https://recbole.io/docs/developer_guide/customize_models.html). I hope this can help you.

**Comment by rowedenny** [comment]
Thanks for your quick response and great efforts. It looks good so far, and I will move on with the customized model and update here if there is a new issue.

I completely understand how hard it is to develop a new framework, while the user, like me, keeps raising a new quest to update. So again really appreciate all your effort.
