### ISSUE TITLE
[QUESTION] Q about sequential models

### ISSUE THREAD

**Issue by mayaKaplansky** [RUCAIBox/RecBole#615]
Hi
I would like to experiment on several sequential models. 
I have user session set of clicks and I want to be able to predict the next click in each stage of the session.
For example, a session has: click1, click2, click3, click4.
I want to be able to predict from click1 to click2, and also given click1 and click 2 I want to predict click3 and so on.
Not just the last click.
In other models I examined, I had to build the train data in a way that I feed each session by click, meaning:
X1: click1
Y1: click2
X2: click1, click2
Y2: click3
X3: click1, click2,click3
Y3: click4

Should I do the same using your library or no need?
Many thanks!!

**Comment by ShanleiMu** [comment]
Please refer to #614.

**Comment by chenyushuo** [comment]
We always do data augmentation in the sequential model. You can see the following code for details:

https://github.com/RUCAIBox/RecBole/blob/90d5c3f18ca0e10d6cad5c74ff0723125ef9aa25/recbole/data/dataset/sequential_dataset.py#L40-L94

**Comment by mayaKaplansky** [comment]
Thats perfect thank you so much!!

**Comment by cramraj8** [comment]
When I run the run_recbole for a GRU4Rec in sequential setting, the data augmentation were never run through. I tried to put print statements in the scripts to see if the data_augmentation function is called ([https://github.com/RUCAIBox/RecBole/blob/0c7197b01c009d822ed95d17011ab6289c86ac58/recbole/data/dataset/sequential_dataset.py#L49](https://github.com/RUCAIBox/RecBole/blob/0c7197b01c009d822ed95d17011ab6289c86ac58/recbole/data/dataset/sequential_dataset.py#L49)), but it never did.

And I am getting the below error because of that

```
"/home/xxx/xxx/RecBole/RecBole/recbole/model/sequential_recommender/gru4rec.py", line 84, in forward
    seq_output = self.gather_indexes(gru_output, item_seq_len - 1)
  File "/home/xxx/xxx/RecBole/RecBole/recbole/model/abstract_recommender.py", line 174, in gather_indexes
    output_tensor = output.gather(dim=1, index=gather_index)
RuntimeError: index 122111 is out of bounds for dimension 1 with size 53
```

Any ideas how I can solve it or am I missing any config statements ?
