### ISSUE TITLE
[💡SUG] Load trained model, but when initialize the model, need train_data, this train_data would be an empty data ? 

### ISSUE THREAD

**Issue by dxjjhm** [RUCAIBox/RecBole#660]
dataset = create_dataset(bpr_config)

train_data, valid_data, test_data = data_preparation(bpr_config, dataset)  **# is it really needed?**

user_behavior_df, item_name_df = read_user_behavior_df()

bpr_model = BPR(bpr_config, train_data)  **# if train_data is emtpy , does work ?**  
checkpoint = torch.load('/data/home/cbgrdd/whdu/recbole/general/saved/BPR-Dec-21-2020_16-14-02.pth')
bpr_model.load_state_dict(checkpoint['state_dict'])
bpr_model.eval()

**Comment by 2017pxy** [comment]
@dxjjhm I am sorry to tell you that now RecBole don't support this kind of usage. If you want to run a model, you' d better run the whole process, including training. I must admit that RecBole is not flexible enough for now, and we will carefully consider your need and improve the flexibility of RecBole in the future.

**Comment by hyp1231** [comment]
Hi @dxjjhm,
* **Q1**: is it (``data_preparation``) really needed?
   **A1**: It's not always needed.
* **Q2**: if ``train_data`` is empty, does the code work?
   **A1**: It will not work, but instead you can replace it with ``Dataset`` (in most cases). Such as:

```python
dataset = create_dataset(bpr_config)

user_behavior_df, item_name_df = read_user_behavior_df()

bpr_model = BPR(bpr_config, dataset)
checkpoint = torch.load('/data/home/cbgrdd/whdu/recbole/general/saved/BPR-Dec-21-2020_16-14-02.pth')
bpr_model.load_state_dict(checkpoint['state_dict'])
bpr_model.eval()
```

As Model will use some global information of the dataset (e.g. number of users/items) to initialize, and generally these global information exists in a ``Dataset`` object.

https://github.com/RUCAIBox/RecBole/blob/e41c9cd1470f2194b20cd566e27a28fc62af5c7d/recbole/data/dataloader/abstract_dataloader.py#L58-L64

To avoid potential data leakage issues, we only pass ``train_data`` into model initialization, which only contains interactions for training, instead of the whole ``Dataset``. ``train_data`` is a ``DataLoader``, and we assign some methods of ``Dataset`` with ``DataLoader`` to let models get global information from a ``DataLoader`` object. You can see this as a kind of syntactic sugar.    :D

However, there exist models like NGCF, who request information about interactions (like ``inter_matrix``) or other ``DataLoader`` specifically owned methods, then you can not pass a ``Dataset`` to initialize such models.

I understand it's quite not easy to do case-study or other customized operations while evaluating, we'll try to improve this in the future, thx!
