### ISSUE TITLE
[🐛BUG] Different default run_recbole results for v.1.2 and v0.2.0

### ISSUE THREAD

**Issue by jlbezares** [RUCAIBox/RecBole#699]
**Describe the bug**
We are getting different score results using default run_recbole for the two Recbole versions (v0.2.0. and v0.1.2.).

**To Reproduce**
Use Recbole v.0.1.2 and v.0.2.0):
 from recbole.quick_start import run_recbole
 run_recbole(model= 'Pop', dataset='ml-100k')

**Expected behavior**
I understand that default score results should be equal (at least very similar) for different Recbole versions.

**Screenshots**
Please, find attached an image with the default score results for Pop, ml-100k using v0.1.2 and 0.2.0 versions. It displays the run_recbole results for diferent devices and Recbole versions (RecBole_Different_Score_RBVersions.jpg)
![RecBole_Different_Score_RBVersions](https://user-images.githubusercontent.com/63681726/105833586-b2565680-5fc9-11eb-9629-cc44e8540fd0.jpg)

**Desktop:**
- OS: Windows 10 
- RecBole Version: v0.2.0 and  v0.1.2
- Python Version 3.8.6
- PyTorch Version 1.7.1+cpu
- Cudatoolkit Version: none

**Comment by tsotfsk** [comment]
I am sorry that I didn't explain this problem in detail in the 0.2, which brings trouble to your experiment. In fact, in 0.2, we changed the method of ranking the same values for items, so that users can more easily find its code errors and better use our HypOpt Module . You can see it in PR #658   and issue #622 . When we submit the PR, we selectively test several kinds of neural network models, but unfortunately, we ignore Pop.

As it is known to us, Pop is a rule-based and non personalized item recommendation algorithm. For the ml-100k dataset, there are only 32 different values for the frequency of items. This means that, unlike the deep neural network model, Pop has a large number of items with the same score. Then the rank method of these items with the same score will become a problem. At first, we used the method `max-rank ` which means  selecting the max rank value of the same score, while in 0.2, we used the method of `min-rank ` which will evaluate the effect of the model more reasonably.

In fact, our members are also actively discussing this issue. We now refer to the rank function in pandas named [pandas.Series.rank](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rank.html), and we will consider further optimizing this issue in later versions, so that users can set the rank method they like under the same score condition.

BTW, according to my personal test results, between 0.1.2 and 0.2 versions, such as BPR (MF), NeuMF and other neural network models, the results are equal. Moreover, for large-scale data sets, even pop, the results are also equal. Therefore, this problem only occurs when a large number of items have the same score and it maybe not common in neural network models.
