### ISSUE TITLE
Recommendation for Highly Volatile Product and Userset?

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#701]
Hi,
Thanks for providing such a beautiful library. I was looking for a recommendation system for highly volatile products and user-set. 
I have a dataset that has a very small overlap with previous products. 70% of products are highly seasonal. User's action per product is also quite low, 2.1.

Which type of recommendation algorithm would you suggest me to use?

**Comment by 2017pxy** [comment]
@laxmimerit Hi, I think you'd better do some experiments by yourself, since RecBole now has 65 models and it's hard for me to tell which model performs better on your dataset.

**Comment by laxmimerit** [comment]
Thanks a lot for your quick response. Definitely I am have implemented some of your models and they are working good. 
I had only doubt that how it will get the product understanding which were not sold previously. I think matrix factorization algos would be right choice for it.
I have another doubt on cold start issue. I have implemented LightGCN but it wasn't able to give me recommendation for users who had never made a purchase. How can I handle this issue?

**Comment by batmanfly** [comment]
@laxmimerit Hi, do you mean cold-start product recommendation, i.e., new products? If so, I think most of the algorithms in our library has not specially consider this point. It means we cannot generate an effective representation for new products. 

For the second issue, you seem to refer cold-start user recommendation, i.e., new users.


Generally speaking, there are two approaches to overcoming the cold-start issue. 

The first one is content based: you utilize content to learn new user or item embeddings;
The second one is query based: you ask a new user at least assign some ratings or you ask several users to assign ratings to an item. 

However, it should be noted either you need to have ratings or content. Otherwise, cold-start recommendation cannot be well solved. 

For lightGCN, it doesn't solve the cold-start users at all. If you would like to adapt it for this purpose, you may refer to GraphSAGE, which is an inductive learning algorithms for graph neural networks. If you read the paper, you will find its implementation is very easy. 

Let me know what is your real needs. =)

Thanks!

**Comment by laxmimerit** [comment]
Hi,
Thanks for detailed description. I was going through knowledge based recommendation system of RecBole. I read abstract of papers and it seems my issue is addressed in these papers and luckily these are already implemented. 
As you suggested previously that Graph based conv Neural Networks can solve cold start issue so don't you think KGCN model would solve my issue?

**Comment by batmanfly** [comment]
> Hi,
> Thanks for detailed description. I was going through knowledge based recommendation system of RecBole. I read abstract of papers and it seems my issue is addressed in these papers and luckily these are already implemented.
> As you suggested previously that Graph based conv Neural Networks can solve cold start issue so don't you think KGCN model would solve my issue?

@laxmimerit Hi, what I mean is that we do not specially consider cold-start setting in our library. However, it would be OK if some method happened to or intended to solve this issue. 

To judge whether one implementation works for cold-start issues, you can create a toy example and test the model. 

Not all the GNN methods apply to cold start. They can do this when are implemented in an inductive way (See grapsage for details).
