### ISSUE TITLE
[💡SUG] Addition of Learning to Rank Model

### ISSUE THREAD

**Issue by jianshen92** [RUCAIBox/RecBole#901]
Learning to Rank is one of the many methods that is popular in the recommendation space. Although not many company has published papers regarding this method, Airbnb has [one](https://arxiv.org/pdf/1810.09591.pdf).

I would like to know the opinion of recbole team in learning-to-rank for recommendation system, and whether it is worth adding to the model pool.

**Comment by 2017pxy** [comment]
@jianshen92 Hi, in RecBole, we have 4 kinds of models, namely, general recommendation, sequential recommendation, context-aware recommendation and knowledge-based recommendation. In our design, we set these four categories mainly based on the perspective of input data, rather than the model structure (like GNN-based, RNN-based, Auto-Encoder-based), the technique they use (like MF, FM, Reinforcement Learning) or the task (Rating prediction, TopN recommendation). 

In my opinion, "Learning to Rank" (L2R in short) is a research field in information retrieval, and it can be used in search engine, recommendation system and so on. I agree that L2R is a popular method in recommendation space, however, we won't set a new model category for L2R since the perspective is different to our classification. 

BTW, if you have any idea of adding new models into RecBole, please leave your suggestion with more details in [discussion](https://github.com/RUCAIBox/RecBole/discussions/611) and we will carefully consider it.  

Finally , thanks for your close attention to RecBole!
