### ISSUE TITLE
Prediction in Random Order

### ISSUE THREAD

**Issue by laxmimerit** [RUCAIBox/RecBole#978]
Hi,
I am using `SaSRec` for prediction on custom data. While prediction, itis changing the order of prediction on every run. For a given input it should be producing the same set of results on every run but its output is changing on every run. How to fix this?

**Comment by Sherry-XLL** [comment]
@laxmimerit Hello, RecBole will init random seed for random functions in numpy, torch, cuda and cudnn by function `init_seed` in `recbole/utils/utils.py`. Therefore, each time the same command is passed, the result is the same. 

I don't understand `While prediction it is generating random prediction`. Although the prediction is random, the specific prediction results of each run should be different. Maybe you can fix the random sequence so that every run is the same, but the same result is meaningless. 

If I misunderstood your question, please explain your problem in more details and provide the code for generating random prediction. Thanks for your attention to RecBole.

**Comment by laxmimerit** [comment]
Hi,
Let's take this as an example. I trained the model on a specific dataset and now want to predict future sequences. First time I gave input sequence `[a,b,c,d]` it produces output `[x,y,z]`. Now if I again pass the same input sequence `[a,b,c,d]` then I am getting some other output sequence `[p,q,r,s,t]`. Shouldn't I be getting the same output sequence for it?

**Comment by Sherry-XLL** [comment]
@laxmimerit I try to train SASRec on `ml-100k` dataset and predict with `case study`, but I get the same results when the same inputs are given. Do you have inconsistent results when you run on RecBole's datasets? In addition, how do you get the output sequence through the trained model? In principle, the results should be the same every time. I'm sorry I misunderstood your question just now.

**Comment by laxmimerit** [comment]
I haven't tested it on recobole's dataset.

**Comment by Sherry-XLL** [comment]
@laxmimerit No matter what the dataset is, the parameters are fixed after the training is completed, and different results should not be produced for the same input. I'm sorry I am not able to replicate your question. Please check whether the input `item_seq` and `item_seq_len` of the function `predict` are the same every time. I hope my answers help you.
