### ISSUE TITLE
Is there any way to get the scores of the user-item pairs that not contained in test_data ?

### ISSUE THREAD

**Issue by zrg1993** [RUCAIBox/RecBole#980]
https://github.com/RUCAIBox/RecBole/blob/b7b29954fbc963a406ddbe2f917b4ba56bd7a22b/recbole/utils/case_study.py#L20

**Comment by chenyuwuxin** [comment]
@zrg1993 Hello, thanks for your attention to RecBole!

- Firstly, you need to ensure that all users you want to know must appear in test_data, and the user-item pairs does not appear in the train_data or valid_data, because the `full_sort_scores` function will mask them by setting their value to -inf.
- Then , you can refer to `run_example/case_study_example.py`
   You need to know the external ID of the user, then convert them into internal ID by calling `dataset.token2id`, and the same process obtains the internal ID of the item. By calling `full_sort_scores(internal_uid,model,test_data,device)`, you can get a score matrix，and i-th row of the matrix represents the rating of all items by the i-th user，and `Score[u , v]` indicates the score of the item with internal-id v by the u-th user.

Thank you again for your attention to RecBole.

**Comment by zrg1993** [comment]
Many thanks for your clear explanation. I want to get the scores of random user-item pairs select by user. That’s why I want to get the scores of the user-item pairs not contained in test_data.

I guess the design of masking user-item pairs appearing in the train_data or valid_data in the function `full_sort_scores` result in that the topk recommendation can filter the history user-item pairs in the function `full_sort_topk`. If the guess is wrong, please pardon me and show me the reason.

But in some case the user want to generate the topk recommendation items including the history user-item pairs. So it might be better to provide a choice for the user to determine include the history user-items pairs or not in the function `full_sort_topk`. Or make the topk recommendation(do not contain the history user-items pairs)  clear in the documentation.

**Comment by chenyuwuxin** [comment]
Thank you very much for your advice and your guess is correct.
Rebole already supports both repeatable recommendation and non repeatable recommendation scenes. 
For repeatable recommendations, you can evaluate historical interaction information that does not belong to the test_data. 

- If you want to enable repeatable recommendation in the training, verification and evaluation of the model, you can set the parameter of the config file `repeatable` to `True`. 

        repeatable: True

- If you want to be in `case_study` module turns on repeatable recommendations ，you can just comment out the following two lines of code of `full_sort_scores`.
```
    #if history_index is not None:
    #    scores[history_index] = -np.inf  # set scores of history items to -inf
```

I hope my answer can help you.

**Comment by zrg1993** [comment]
Thank you very much for the kind know-how sharing. It saved me a lot of time.
